#!/command/with-contenv /bin/bash

set -eu

if [[ -z "${RCP_HOST:-}" ]]; then
    echo "ERROR: RCP_HOST environment variable is not set"
    exit 1
fi


echo "Starting socat ..."

exec /usr/bin/socat -d -d \
  -ly -lf /var/log/socat-otrcp.log \
  pty,link=${RCP_TTY:-/tmp/ttyOTBR},raw,echo=0,wait-slave,ignoreeof \
  tcp:${RCP_HOST}:${RCP_PORT:-6638},nodelay,keepalive,forever,interval=5

###exec /usr/bin/socat -d3 \
###  pty,raw,echo=0,link=${RCP_TTY:-/tmp/ttyOTBR},ignoreeof,wait-slave \
###  tcp:${RCP_HOST}:${RCP_PORT:-6638},forever,interval=5,nodelay,keepalive
